# Generated by Django 2.0.5 on 2018-05-17 09:51

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_realid', models.CharField(blank=True, help_text="Trello's real ID for this board. Discovered automatically if you don't know it", max_length=255)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('enabled', models.BooleanField(default=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('days_in_future', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='TrelloClient',
            fields=[
                ('client_auth_token', models.CharField(help_text='Visit <a href="https://trello.com/1/authorize?key=f5936fb9f3d0e7535dd87b8b55c1b6e4&name=Trelleux&expiration=never&response_type=token&scope=read,write">here</a> to get a token.', max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trelloboard',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='trelleux.TrelloClient'),
        ),
    ]
